package com.fxalways.app.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.text.intl.Locale

data class FxStrings(
    val appName: String,
    val proActive: String,
    val cachedRatesStatus: String,
    val refresh: String,
    val globalWatchlist: String,
    val converter: String,
    val sourceLine: (provider: String, date: String) -> String,
    val loadingRates: String,
    val amount: String,
    val from: String,
    val to: String,
    val waitingForData: String,
    val historyLine: (isPremium: Boolean) -> String,
    val proTitle: String,
    val proSubtitle: String,
    val subscribe: String,
    val featuresTitle: String,
    val cacheFeature: String,
    val historyFeature: String,
    val paywallFeature: String,
    val retry: String,
    val loadError: String,
)

data class LanguageOption(
    val code: String,
    val label: String,
)

val SupportedLanguages = listOf(
    LanguageOption("en", "English"),
    LanguageOption("es", "Español"),
    LanguageOption("pt", "Português"),
    LanguageOption("zh", "中文"),
    LanguageOption("hi", "हिन्दी"),
    LanguageOption("fr", "Français"),
    LanguageOption("ar", "العربية"),
    LanguageOption("bn", "বাংলা"),
    LanguageOption("ru", "Русский"),
    LanguageOption("ur", "اردو"),
    LanguageOption("id", "Indonesia"),
    LanguageOption("de", "Deutsch"),
    LanguageOption("ja", "日本語"),
)

@Composable
fun rememberFxStrings(languageOverride: String? = null): FxStrings {
    val language = languageOverride ?: Locale.current.language.lowercase()
    return remember(language) { fxStringsFor(language) }
}

fun fxStringsFor(language: String): FxStrings =
    localizedStrings[language.lowercase()] ?: localizedStrings.getValue("en")

private val localizedStrings = mapOf(
    "en" to FxStrings(
        appName = "FX Always",
        proActive = "Pro active",
        cachedRatesStatus = "Fresh rates with backend cache",
        refresh = "Refresh",
        globalWatchlist = "Global watchlist",
        converter = "Converter",
        sourceLine = { provider, date -> "Source $provider, $date" },
        loadingRates = "Loading rates",
        amount = "Amount",
        from = "From",
        to = "To",
        waitingForData = "Waiting for data",
        historyLine = { isPremium -> "History ${if (isPremium) "5 years" else "12 months"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "Monthly iOS plan: extended history, alerts and unlimited portfolios.",
        subscribe = "Subscribe",
        featuresTitle = "Included features",
        cacheFeature = "Firebase cache reduces paid API calls and keeps the app fast.",
        historyFeature = "Pair history, watchlist, instant conversion and a foundation for alerts.",
        paywallFeature = "iOS paywall prepared for RevenueCat with a monthly entitlement.",
        retry = "Retry",
        loadError = "Could not load exchange rates.",
    ),
    "es" to FxStrings(
        appName = "FX Always",
        proActive = "Pro activo",
        cachedRatesStatus = "Rates al día con caché backend",
        refresh = "Actualizar",
        globalWatchlist = "Watchlist global",
        converter = "Conversor",
        sourceLine = { provider, date -> "Fuente $provider, $date" },
        loadingRates = "Cargando rates",
        amount = "Monto",
        from = "De",
        to = "A",
        waitingForData = "Esperando datos",
        historyLine = { isPremium -> "Histórico ${if (isPremium) "5 años" else "12 meses"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "Plan mensual iOS: históricos extendidos, alertas y portfolios ilimitados.",
        subscribe = "Suscribirme",
        featuresTitle = "Features incluidos",
        cacheFeature = "El caché en Firebase reduce llamadas a la API paga y mantiene la app rápida.",
        historyFeature = "Históricos por par, watchlist, conversión inmediata y base lista para alertas.",
        paywallFeature = "Paywall iOS preparado para RevenueCat con entitlement mensual.",
        retry = "Reintentar",
        loadError = "No se pudieron cargar los tipos de cambio.",
    ),
    "pt" to FxStrings(
        appName = "FX Always",
        proActive = "Pro ativo",
        cachedRatesStatus = "Cotações atualizadas com cache backend",
        refresh = "Atualizar",
        globalWatchlist = "Watchlist global",
        converter = "Conversor",
        sourceLine = { provider, date -> "Fonte $provider, $date" },
        loadingRates = "Carregando cotações",
        amount = "Valor",
        from = "De",
        to = "Para",
        waitingForData = "Aguardando dados",
        historyLine = { isPremium -> "Histórico ${if (isPremium) "5 anos" else "12 meses"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "Plano mensal iOS: histórico estendido, alertas e portfólios ilimitados.",
        subscribe = "Assinar",
        featuresTitle = "Recursos incluídos",
        cacheFeature = "O cache no Firebase reduz chamadas à API paga e mantém o app rápido.",
        historyFeature = "Histórico por par, watchlist, conversão imediata e base pronta para alertas.",
        paywallFeature = "Paywall iOS preparado para RevenueCat com entitlement mensal.",
        retry = "Tentar novamente",
        loadError = "Não foi possível carregar as taxas de câmbio.",
    ),
    "zh" to FxStrings(
        appName = "FX Always",
        proActive = "Pro 已启用",
        cachedRatesStatus = "通过后端缓存获取最新汇率",
        refresh = "刷新",
        globalWatchlist = "全球关注列表",
        converter = "换算器",
        sourceLine = { provider, date -> "来源 $provider，$date" },
        loadingRates = "正在加载汇率",
        amount = "金额",
        from = "从",
        to = "到",
        waitingForData = "等待数据",
        historyLine = { isPremium -> "历史 ${if (isPremium) "5 年" else "12 个月"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "iOS 月度方案：更长历史、提醒和无限投资组合。",
        subscribe = "订阅",
        featuresTitle = "包含功能",
        cacheFeature = "Firebase 缓存可减少付费 API 调用并保持应用快速。",
        historyFeature = "货币对历史、关注列表、即时换算，以及提醒功能基础。",
        paywallFeature = "iOS 付费墙已为 RevenueCat 月度权益做好准备。",
        retry = "重试",
        loadError = "无法加载汇率。",
    ),
    "hi" to FxStrings(
        appName = "FX Always",
        proActive = "Pro सक्रिय",
        cachedRatesStatus = "बैकएंड कैश के साथ ताजा दरें",
        refresh = "रीफ्रेश",
        globalWatchlist = "वैश्विक वॉचलिस्ट",
        converter = "कनवर्टर",
        sourceLine = { provider, date -> "स्रोत $provider, $date" },
        loadingRates = "दरें लोड हो रही हैं",
        amount = "राशि",
        from = "से",
        to = "तक",
        waitingForData = "डेटा की प्रतीक्षा",
        historyLine = { isPremium -> "इतिहास ${if (isPremium) "5 वर्ष" else "12 महीने"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "iOS मासिक योजना: लंबा इतिहास, अलर्ट और असीमित पोर्टफोलियो।",
        subscribe = "सदस्यता लें",
        featuresTitle = "शामिल सुविधाएँ",
        cacheFeature = "Firebase कैश paid API calls कम करता है और app तेज रखता है।",
        historyFeature = "Pair history, watchlist, instant conversion और alerts के लिए आधार।",
        paywallFeature = "iOS paywall RevenueCat monthly entitlement के लिए तैयार है।",
        retry = "फिर कोशिश करें",
        loadError = "Exchange rates लोड नहीं हो सके।",
    ),
    "fr" to FxStrings(
        appName = "FX Always",
        proActive = "Pro actif",
        cachedRatesStatus = "Taux à jour avec cache backend",
        refresh = "Actualiser",
        globalWatchlist = "Watchlist mondiale",
        converter = "Convertisseur",
        sourceLine = { provider, date -> "Source $provider, $date" },
        loadingRates = "Chargement des taux",
        amount = "Montant",
        from = "De",
        to = "Vers",
        waitingForData = "En attente de données",
        historyLine = { isPremium -> "Historique ${if (isPremium) "5 ans" else "12 mois"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "Abonnement mensuel iOS : historique étendu, alertes et portefeuilles illimités.",
        subscribe = "S'abonner",
        featuresTitle = "Fonctionnalités incluses",
        cacheFeature = "Le cache Firebase réduit les appels à l'API payante et garde l'app rapide.",
        historyFeature = "Historique par paire, watchlist, conversion instantanée et base pour alertes.",
        paywallFeature = "Paywall iOS prêt pour RevenueCat avec entitlement mensuel.",
        retry = "Réessayer",
        loadError = "Impossible de charger les taux de change.",
    ),
    "ar" to FxStrings(
        appName = "FX Always",
        proActive = "Pro نشط",
        cachedRatesStatus = "أسعار حديثة مع تخزين مؤقت في الخلفية",
        refresh = "تحديث",
        globalWatchlist = "قائمة مراقبة عالمية",
        converter = "محول",
        sourceLine = { provider, date -> "المصدر $provider، $date" },
        loadingRates = "جار تحميل الأسعار",
        amount = "المبلغ",
        from = "من",
        to = "إلى",
        waitingForData = "بانتظار البيانات",
        historyLine = { isPremium -> "السجل ${if (isPremium) "5 سنوات" else "12 شهرًا"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "خطة iOS شهرية: سجل موسع وتنبيهات ومحافظ غير محدودة.",
        subscribe = "اشتراك",
        featuresTitle = "الميزات المضمنة",
        cacheFeature = "يقلل تخزين Firebase المؤقت استدعاءات API المدفوعة ويحافظ على سرعة التطبيق.",
        historyFeature = "سجل الأزواج وقائمة المراقبة والتحويل الفوري وأساس للتنبيهات.",
        paywallFeature = "جدار الدفع على iOS جاهز لـ RevenueCat مع استحقاق شهري.",
        retry = "إعادة المحاولة",
        loadError = "تعذر تحميل أسعار الصرف.",
    ),
    "bn" to FxStrings(
        appName = "FX Always",
        proActive = "Pro সক্রিয়",
        cachedRatesStatus = "ব্যাকএন্ড ক্যাশসহ আপডেট রেট",
        refresh = "রিফ্রেশ",
        globalWatchlist = "গ্লোবাল ওয়াচলিস্ট",
        converter = "কনভার্টার",
        sourceLine = { provider, date -> "উৎস $provider, $date" },
        loadingRates = "রেট লোড হচ্ছে",
        amount = "পরিমাণ",
        from = "থেকে",
        to = "প্রতি",
        waitingForData = "ডেটার অপেক্ষা",
        historyLine = { isPremium -> "ইতিহাস ${if (isPremium) "৫ বছর" else "১২ মাস"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "iOS মাসিক প্ল্যান: বাড়তি ইতিহাস, অ্যালার্ট এবং সীমাহীন পোর্টফোলিও।",
        subscribe = "সাবস্ক্রাইব",
        featuresTitle = "অন্তর্ভুক্ত ফিচার",
        cacheFeature = "Firebase ক্যাশ paid API call কমায় এবং app দ্রুত রাখে।",
        historyFeature = "Pair history, watchlist, instant conversion এবং alerts-এর ভিত্তি।",
        paywallFeature = "iOS paywall RevenueCat monthly entitlement-এর জন্য প্রস্তুত।",
        retry = "আবার চেষ্টা করুন",
        loadError = "Exchange rates লোড করা যায়নি।",
    ),
    "ru" to FxStrings(
        appName = "FX Always",
        proActive = "Pro активен",
        cachedRatesStatus = "Свежие курсы через backend cache",
        refresh = "Обновить",
        globalWatchlist = "Глобальный watchlist",
        converter = "Конвертер",
        sourceLine = { provider, date -> "Источник $provider, $date" },
        loadingRates = "Загрузка курсов",
        amount = "Сумма",
        from = "Из",
        to = "В",
        waitingForData = "Ожидание данных",
        historyLine = { isPremium -> "История ${if (isPremium) "5 лет" else "12 месяцев"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "Месячный план iOS: расширенная история, уведомления и неограниченные портфели.",
        subscribe = "Подписаться",
        featuresTitle = "Включенные функции",
        cacheFeature = "Firebase cache снижает платные API-вызовы и ускоряет приложение.",
        historyFeature = "История пар, watchlist, мгновенная конвертация и база для уведомлений.",
        paywallFeature = "iOS paywall подготовлен для RevenueCat с месячным entitlement.",
        retry = "Повторить",
        loadError = "Не удалось загрузить курсы валют.",
    ),
    "ur" to FxStrings(
        appName = "FX Always",
        proActive = "Pro فعال",
        cachedRatesStatus = "backend cache کے ساتھ تازہ rates",
        refresh = "Refresh",
        globalWatchlist = "Global watchlist",
        converter = "Converter",
        sourceLine = { provider, date -> "Source $provider، $date" },
        loadingRates = "Rates load ہو رہے ہیں",
        amount = "رقم",
        from = "سے",
        to = "تک",
        waitingForData = "Data کا انتظار",
        historyLine = { isPremium -> "History ${if (isPremium) "5 سال" else "12 ماہ"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "iOS monthly plan: extended history، alerts اور unlimited portfolios۔",
        subscribe = "Subscribe",
        featuresTitle = "Included features",
        cacheFeature = "Firebase cache paid API calls کم کرتا ہے اور app fast رکھتا ہے۔",
        historyFeature = "Pair history، watchlist، instant conversion اور alerts کی بنیاد۔",
        paywallFeature = "iOS paywall RevenueCat monthly entitlement کے لیے تیار ہے۔",
        retry = "دوبارہ کوشش",
        loadError = "Exchange rates load نہیں ہو سکے۔",
    ),
    "id" to FxStrings(
        appName = "FX Always",
        proActive = "Pro aktif",
        cachedRatesStatus = "Kurs terbaru dengan cache backend",
        refresh = "Segarkan",
        globalWatchlist = "Watchlist global",
        converter = "Konverter",
        sourceLine = { provider, date -> "Sumber $provider, $date" },
        loadingRates = "Memuat kurs",
        amount = "Jumlah",
        from = "Dari",
        to = "Ke",
        waitingForData = "Menunggu data",
        historyLine = { isPremium -> "Riwayat ${if (isPremium) "5 tahun" else "12 bulan"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "Paket bulanan iOS: riwayat panjang, alert, dan portofolio tanpa batas.",
        subscribe = "Berlangganan",
        featuresTitle = "Fitur termasuk",
        cacheFeature = "Cache Firebase mengurangi panggilan API berbayar dan menjaga app tetap cepat.",
        historyFeature = "Riwayat pair, watchlist, konversi instan, dan dasar untuk alert.",
        paywallFeature = "Paywall iOS siap untuk RevenueCat dengan entitlement bulanan.",
        retry = "Coba lagi",
        loadError = "Tidak dapat memuat kurs.",
    ),
    "de" to FxStrings(
        appName = "FX Always",
        proActive = "Pro aktiv",
        cachedRatesStatus = "Aktuelle Kurse mit Backend-Cache",
        refresh = "Aktualisieren",
        globalWatchlist = "Globale Watchlist",
        converter = "Umrechner",
        sourceLine = { provider, date -> "Quelle $provider, $date" },
        loadingRates = "Kurse werden geladen",
        amount = "Betrag",
        from = "Von",
        to = "Nach",
        waitingForData = "Warte auf Daten",
        historyLine = { isPremium -> "Historie ${if (isPremium) "5 Jahre" else "12 Monate"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "Monatlicher iOS-Plan: erweiterte Historie, Alerts und unbegrenzte Portfolios.",
        subscribe = "Abonnieren",
        featuresTitle = "Enthaltene Funktionen",
        cacheFeature = "Firebase-Cache reduziert bezahlte API-Aufrufe und hält die App schnell.",
        historyFeature = "Paarhistorie, Watchlist, Sofortumrechnung und Grundlage für Alerts.",
        paywallFeature = "iOS-Paywall vorbereitet für RevenueCat mit monatlichem Entitlement.",
        retry = "Erneut versuchen",
        loadError = "Wechselkurse konnten nicht geladen werden.",
    ),
    "ja" to FxStrings(
        appName = "FX Always",
        proActive = "Pro 有効",
        cachedRatesStatus = "バックエンドキャッシュで最新レート",
        refresh = "更新",
        globalWatchlist = "グローバルウォッチリスト",
        converter = "換算",
        sourceLine = { provider, date -> "ソース $provider、$date" },
        loadingRates = "レートを読み込み中",
        amount = "金額",
        from = "換算元",
        to = "換算先",
        waitingForData = "データ待ち",
        historyLine = { isPremium -> "履歴 ${if (isPremium) "5年" else "12か月"}" },
        proTitle = "FX Always Pro",
        proSubtitle = "iOS 月額プラン: 長期履歴、アラート、無制限ポートフォリオ。",
        subscribe = "登録",
        featuresTitle = "含まれる機能",
        cacheFeature = "Firebase キャッシュで有料 API 呼び出しを減らし、アプリを高速に保ちます。",
        historyFeature = "ペア履歴、ウォッチリスト、即時換算、アラートの基盤。",
        paywallFeature = "iOS paywall は RevenueCat の月額 entitlement に対応準備済みです。",
        retry = "再試行",
        loadError = "為替レートを読み込めませんでした。",
    ),
)
