package com.fxalways.app.screens.settings

import com.fxalways.app.screens.*
internal data class SettingsCopy(
    val title: String,
    val sub: String,
    val more: String,
    val backup: String,
    val syncNow: String,
    val syncNowSubtitle: String,
    val syncing: String,
    val sync: String,
    val signInWith: String,
    val signInSubtitle: String,
    val signInProgressSubtitle: String,
    val connect: String,
    val connecting: String,
    val signOut: String,
    val signOutSubtitle: String,
    val signOutAction: String,
    val subscription: String,
    val view: String,
    val upgrade: String,
    val restorePurchase: String,
    val restorePurchaseSubtitle: String,
    val restore: String,
    val manageSubscription: String,
    val manageSubscriptionSubtitle: String,
    val open: String,
    val notifications: String,
    val priceAlertNotifications: String,
    val themeMode: String,
    val language: String,
    val activeLanguage: String,
    val deviceLanguage: String,
    val languageApplied: String,
    val baseCurrency: String,
    val moreCurrencies: String,
    val search: String,
    val freeIncludes: String,
    val unlocks: String,
    val unlockAllBaseCurrencies: String,
    val supportedBaseCurrencies: String,
    val legal: String,
    val privacyPolicy: String,
    val privacyPolicySubtitle: String,
    val termsOfUse: String,
    val termsOfUseSubtitle: String,
)

internal fun settingsCopy(language: String): SettingsCopy =
    when (language.lowercase()) {
        "es" -> SettingsCopy(
            title = "Ajustes",
            sub = "PREFERENCIAS",
            more = "Más",
            backup = "BACKUP",
            syncNow = "Sincronizar ahora",
            syncNowSubtitle = "Guarda ajustes, alertas y watchlist en Firebase",
            syncing = "sincronizando",
            sync = "sincronizar",
            signInWith = "Iniciar sesión con",
            signInSubtitle = "Mantén el mismo backup y restáuralo en un nuevo",
            signInProgressSubtitle = "Conectando la cuenta de forma segura. Espera un momento.",
            connect = "conectar",
            connecting = "conectando",
            signOut = "Cerrar sesión",
            signOutSubtitle = "Mantén los datos locales y continúa con backup invitado",
            signOutAction = "salir",
            subscription = "SUSCRIPCIÓN",
            view = "ver",
            upgrade = "pro",
            restorePurchase = "Restaurar compra",
            restorePurchaseSubtitle = "Recupera una suscripción existente de Play/App Store",
            restore = "restaurar",
            manageSubscription = "Gestionar suscripción",
            manageSubscriptionSubtitle = "Abre el centro de suscripciones de la tienda",
            open = "abrir",
            notifications = "NOTIFICACIONES",
            priceAlertNotifications = "Notificaciones de alertas",
            themeMode = "TEMA",
            language = "IDIOMA",
            activeLanguage = "Idioma activo",
            deviceLanguage = "Idioma del dispositivo",
            languageApplied = "aplicado",
            baseCurrency = "MONEDA BASE",
            moreCurrencies = "Más monedas",
            search = "Buscar monedas soportadas",
            freeIncludes = "Free incluye",
            unlocks = "desbloquea",
            unlockAllBaseCurrencies = "Desbloquear todas las monedas base",
            supportedBaseCurrencies = "monedas base soportadas",
            legal = "LEGAL",
            privacyPolicy = "Política de privacidad",
            privacyPolicySubtitle = "Cómo FX Always maneja cuenta, rates y datos",
            termsOfUse = "Términos de uso",
            termsOfUseSubtitle = "Suscripción, disclaimers y uso aceptable",
        )
        "pt" -> SettingsCopy(
            title = "Ajustes",
            sub = "PREFERÊNCIAS",
            more = "Mais",
            backup = "BACKUP",
            syncNow = "Sincronizar agora",
            syncNowSubtitle = "Salva ajustes, alertas e watchlist no Firebase",
            syncing = "sincronizando",
            sync = "sincronizar",
            signInWith = "Entrar com",
            signInSubtitle = "Mantenha o mesmo backup e restaure em um novo",
            signInProgressSubtitle = "Conectando a conta com segurança. Aguarde um momento.",
            connect = "conectar",
            connecting = "conectando",
            signOut = "Sair",
            signOutSubtitle = "Mantém dados locais e continua com backup convidado",
            signOutAction = "sair",
            subscription = "ASSINATURA",
            view = "ver",
            upgrade = "pro",
            restorePurchase = "Restaurar compra",
            restorePurchaseSubtitle = "Recupera uma assinatura existente da Play/App Store",
            restore = "restaurar",
            manageSubscription = "Gerenciar assinatura",
            manageSubscriptionSubtitle = "Abre o centro de assinaturas da loja",
            open = "abrir",
            notifications = "NOTIFICAÇÕES",
            priceAlertNotifications = "Notificações de alertas",
            themeMode = "TEMA",
            language = "IDIOMA",
            activeLanguage = "Idioma ativo",
            deviceLanguage = "Idioma do dispositivo",
            languageApplied = "aplicado",
            baseCurrency = "MOEDA BASE",
            moreCurrencies = "Mais moedas",
            search = "Buscar moedas suportadas",
            freeIncludes = "Free inclui",
            unlocks = "desbloqueia",
            unlockAllBaseCurrencies = "Desbloquear todas as moedas base",
            supportedBaseCurrencies = "moedas base suportadas",
            legal = "LEGAL",
            privacyPolicy = "Política de privacidade",
            privacyPolicySubtitle = "Como FX Always lida com conta, rates e dados",
            termsOfUse = "Termos de uso",
            termsOfUseSubtitle = "Assinatura, disclaimers e uso aceitável",
        )
        else -> {
            fun t(key: String): String = localizedUiText(language, key)
            SettingsCopy(
                title = t("Settings"),
                sub = t("APP PREFERENCES"),
                more = t("More"),
                backup = t("BACKUP"),
                syncNow = t("Sync now"),
                syncNowSubtitle = t("Push the latest settings, alerts and watchlist to Firebase"),
                syncing = t("syncing"),
                sync = t("sync"),
                signInWith = t("Sign in with"),
                signInSubtitle = t("Keep the same backup and restore it on a new"),
                signInProgressSubtitle = t("Connecting your account securely. Please wait."),
                connect = t("connect"),
                connecting = t("connecting"),
                signOut = t("Sign out"),
                signOutSubtitle = t("Keep local data and continue with a new guest backup"),
                signOutAction = t("sign out"),
                subscription = t("SUBSCRIPTION"),
                view = t("view"),
                upgrade = t("upgrade"),
                restorePurchase = t("Restore purchase"),
                restorePurchaseSubtitle = t("Recover an existing Play/App Store subscription"),
                restore = t("restore"),
                manageSubscription = t("Manage subscription"),
                manageSubscriptionSubtitle = t("Open the store subscription center for billing changes"),
                open = t("open"),
                notifications = t("NOTIFICATIONS"),
                priceAlertNotifications = t("Price alert notifications"),
                themeMode = t("THEME MODE"),
                language = t("LANGUAGE"),
                activeLanguage = t("Active language"),
                deviceLanguage = t("Device language"),
                languageApplied = t("applied"),
                baseCurrency = t("BASE CURRENCY"),
                moreCurrencies = t("More currencies"),
                search = t("Search supported base currencies"),
                freeIncludes = t("Free includes"),
                unlocks = t("unlocks"),
                unlockAllBaseCurrencies = t("Unlock all base currencies"),
                supportedBaseCurrencies = t("supported base currencies"),
                legal = t("LEGAL"),
                privacyPolicy = t("Privacy Policy"),
                privacyPolicySubtitle = t("How FX Always handles account, rates and analytics data"),
                termsOfUse = t("Terms of Use"),
                termsOfUseSubtitle = t("Subscription terms, disclaimers and acceptable use"),
            )
        }
    }
